(ns re-native.core
  (:require [reagent.core :as r]
            [re-frame.core :as re]))

(def react-native (js/require "react-native"))
(def SwipeableListViewDataSource (js/require "react-native/Libraries/Experimental/SwipeableRow/SwipeableListViewDataSource"))

(def AppRegistry (.-AppRegistry react-native))

(def registerComponentAppRegistry (.-registerComponent AppRegistry))
(def PermissionsAndroid (.-PermissionsAndroid react-native))
(def Linking (.-Linking react-native))
(def RefreshControl (.-RefreshControl react-native))
(def StatusBar (.-StatusBar react-native))
(def Button (.-Button react-native))
(def ListView (.-ListView react-native))
(def KeyboardAvoidingView (.-KeyboardAvoidingView react-native))
(def Keyboard (.-Keyboard react-native))
(def addListenerKeyboard (.-addListener Keyboard))
(def Slider (.-Slider react-native))
(def Text (.-Text react-native))
(def TextInput (.-TextInput react-native))
(def View (.-View react-native))
(def Image (.-Image react-native))
(def ScrollView (.-ScrollView react-native))
(def ActivityIndicator (.-ActivityIndicator react-native))
(def TouchableHighlight (.-TouchableHighlight react-native))
(def TouchableWithoutFeedback (.-TouchableWithoutFeedback react-native))
(def TouchableOpacity (.-TouchableOpacity react-native))
(def Animated (.-Animated react-native))
(def AnimatedView (.-View Animated))
(def AnimatedImage (.-Image Animated))
(def AnimatedValue (.-Value Animated))
(def Easing (.-Easing react-native))
(def quadEasing (.-quad Easing))
(def inOutEasing (.inOut Easing))
(def springAnimated (.-spring Animated))
(def timingAnimated (.-timing Animated))
(def decayAnimated (.-decay Animated))
(def parallelAnimated (.-parallel Animated))
(def sequenceAnimated (.-sequence Animated))
(def AsyncStorage (.-AsyncStorage react-native))
(def getItemAsyncStorage (.-getItem AsyncStorage))
(def setItemAsyncStorage (.-setItem AsyncStorage))
(def removeItemAsyncStorage (.-removeItem AsyncStorage))

(def SwipeableListView (.-SwipeableListView react-native))
(def Modal (.-Modal react-native))
(def Alert (.-Alert react-native))
(def alertAlert (.-alert Alert))
(def DataSource (.-DataSource ListView))
(def getNewDataSourceSwipeableListView (.-getNewDataSource SwipeableListView))

(def Platform (.-Platform react-native))
(def OS (.-OS Platform))

(defn interpolateAnimatedValue [animated-value args]
  (.interpolate animated-value args))

(defn startAnimated [a complete-fn]
  (if complete-fn
   (.start a complete-fn)
   (.start a)))

(defn getRowCountDataSource [ds]
  (.getRowCount (.-_dataSource ds)))

(defn cloneWithRowsAndSectionsDataSource [ds rows sections]
  (.cloneWithRowsAndSections ds rows sections))

(assert react-native)
(assert SwipeableListViewDataSource)
(assert AppRegistry)
(assert Linking)
(assert registerComponentAppRegistry)
(assert RefreshControl)
(assert StatusBar)
(assert Button)
(assert ListView)
(assert KeyboardAvoidingView)
(assert Keyboard)
(assert addListenerKeyboard)
(assert Slider)
(assert Text)
(assert TextInput)
(assert View)
(assert Image)
(assert ScrollView)
(assert ActivityIndicator)
(assert TouchableHighlight)
(assert TouchableWithoutFeedback)
(assert TouchableOpacity)
(assert Animated)
(assert AnimatedView)
(assert AnimatedImage)
(assert AnimatedValue)
(assert Easing)
(assert quadEasing)
(assert inOutEasing)
(assert springAnimated)
(assert timingAnimated)
(assert decayAnimated)
(assert parallelAnimated)
(assert sequenceAnimated)
(assert AsyncStorage)
(assert getItemAsyncStorage)
(assert setItemAsyncStorage)
(assert removeItemAsyncStorage)
(assert SwipeableListView)
(assert Modal)
(assert Alert)
(assert alertAlert)
(assert DataSource)
(assert getNewDataSourceSwipeableListView)
(assert Platform)
(assert OS)
